version: '3.9'

services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8888:8080'
    networks:
      - backend

  api-service-test:
    container_name: api-container-2
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8889:8081'
    networks:
      - backend

  api-service-prod:
    container_name: api-container-3
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8890:8082'
    networks:
      - backend

networks:
  backend:
    driver: bridge